// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetProjectRoot():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.FileInfo>>;

export function ReadFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
